# .github/workflows/docker-build.yml
name: Docker Image Build and Push (Conditional Arch)

on:
  push:
    branches:
      - "main"
      - "nightly"
  pull_request:
    branches:
      - "main"
      # - "nightly" # Optional: Decide if PRs to nightly should trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alplat/baconflip # Your Docker image name
          tags: |
            type=ref,event=branch,pattern=main,value=latest
            type=ref,event=branch,pattern=nightly,value=nightly
            type=sha,format=short

      - name: Build and Push Docker Image (Conditional Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          # --- CONDITIONALLY SET PLATFORMS (Alternative Syntax) ---
          platforms: ${{ github.ref_name == 'main' && 'linux/amd64,linux/arm64' || 'linux/amd64' }} # <--- TRY THIS VERSION
          # Only push when the event is a push to the specific branches
          push: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'nightly') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max