# .github/workflows/docker-build.yml
name: Docker Image Build and Push (Conditional Arch)

on:
  push:
    branches:
      - "stable"
      - "unstable"
  pull_request:
    branches:
      - "stable"
      # - "unstable" # Optional: Decide if PRs to nightly should trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <--- ADD THIS LINE to fetch all history and tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: alplat/baconflip # Your Docker image name
          tags: |
            type=ref,event=branch,pattern=stable,value=latest
            type=ref,event=branch,pattern=unstable,value=unstable
            type=sha,format=short

      - name: Build and Push Docker Image (Conditional Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ github.ref_name == 'stable' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: ${{ github.event_name == 'push' && (github.ref_name == 'stable' || github.ref_name == 'unstable') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha # Consider enabling caching once it works