name: Docker Image Build and Push (Multi-Arch)

on:
  push:
    branches:
      - "main"
      - "nightly"
  pull_request:
    branches:
      - "main"
      # - "nightly" # Optional: Decide if PRs to nightly should trigger

jobs:
  build:
    runs-on: ubuntu-latest # The runner architecture itself doesn't limit build targets with QEMU

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- NEW STEP: Set up QEMU ---
      # Enables the runner to emulate different CPU architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # Use v2 or later

      # --- NEW STEP: Set up Docker Buildx ---
      # Creates a builder instance with multi-platform capabilities
      - name: Set up Docker Buildx
        id: buildx # Give it an id to reference the builder instance if needed, though often not directly
        uses: docker/setup-buildx-action@v2 # Use v2 or later

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: alplat/baconflip # Your Docker image name
          tags: |
            type=ref,event=branch,pattern=main,value=latest
            type=ref,event=branch,pattern=nightly,value=nightly
            type=sha,format=short

      # --- UPDATED STEP: Build and Push Docker Image ---
      - name: Build and Push Docker Image (Multi-Arch)
        uses: docker/build-push-action@v5 # Use latest version (v5 recommended)
        with:
          context: .
          # --- ADDED: Specify target platforms ---
          platforms: linux/amd64 # Add other platforms like linux/arm/v7 if needed
          # Push is necessary to combine the multi-arch manifest in the registry
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optional: Enable build cache for potentially faster builds
          # cache-from: type=gha
          # cache-to: type=gha,mode=max